/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "outline": "hsl(var(--outline) / <alpha-value>)",
        "on-tertiary-fixed-variant": "#006358",
        "secondary-container": "#0b008a",
        "primary-dim": "#e6c047",
        "tertiary-container": "#5bf4de",
        "surface-tint": "#ffdd79",
        "primary-fixed": "#f5ce53",
        "on-surface": "hsl(var(--on-surface) / <alpha-value>)",
        "tertiary-fixed-dim": "#48e5d0",
        "surface": "hsl(var(--surface) / <alpha-value>)",
        "error-container": "#8a1632",
        "on-surface-variant": "hsl(var(--on-surface-variant) / <alpha-value>)",
        "tertiary": "#8affec",
        "tertiary-fixed": "#5bf4de",
        "secondary-dim": "#6063ee",
        "surface-container-lowest": "hsl(var(--surface-container-lowest) / <alpha-value>)",
        "error-dim": "#c8475d",
        "inverse-primary": "#745c00",
        "surface-container-highest": "hsl(var(--surface-container-highest) / <alpha-value>)",
        "on-secondary-fixed": "#2622b7",
        "error": "#fd6f85",
        "outline-variant": "hsl(var(--outline-variant) / <alpha-value>)",
        "on-primary": "hsl(var(--on-primary) / <alpha-value>)",
        "surface-container-high": "hsl(var(--surface-container-high) / <alpha-value>)",
        "on-primary-fixed-variant": "#634e00",
        "surface-variant": "hsl(var(--surface-variant) / <alpha-value>)",
        "primary-fixed-dim": "#e6c047",
        "on-primary-fixed": "#413200",
        "on-error-container": "#ff97a3",
        "on-tertiary": "#006257",
        "on-background": "#e1e4fb",
        "inverse-on-surface": "#53545f",
        "on-secondary-container": "#979aff",
        "surface-container": "hsl(var(--surface-container) / <alpha-value>)",
        "on-primary-container": "#584500",
        "surface-container-low": "hsl(var(--surface-container-low) / <alpha-value>)",
        "secondary-fixed": "#e1e0ff",
        "tertiary-dim": "#48e5d0",
        "surface-bright": "hsl(var(--surface-bright) / <alpha-value>)",
        "secondary-fixed-dim": "#d1d0ff",
        "on-secondary-fixed-variant": "#4647d3",
        "on-tertiary-container": "#00594f",
        "on-tertiary-fixed": "#00443c",
        "on-secondary": "#2724b8",
        "on-error": "#490013",
        "surface-dim": "hsl(var(--surface-dim) / <alpha-value>)",
        "inverse-surface": "#faf8ff",
        "primary-container": "#f5ce53"
      },
      fontFamily: {
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["'Manrope'", "sans-serif"],
        label: ["'Manrope'", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        lg: "2rem", 
        xl: "3rem", 
        full: "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms')({ strategy: 'class' }),
    require('@tailwindcss/container-queries')
  ],
}
